import './globals.css'
import localFont from 'next/font/local'

// Font
const jakarta = localFont({ src: './fonts/PlusJakartaSans-VariableFont_wght.ttf' })

//Components
import { Header } from '@/components/Header'

export const metadata = {
  title: 'Leadster',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jakarta.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
